2024-04-11 19:16:42 - ERROR - Exception on /api/jobs [GET]
Traceback (most recent call last):
  File "/home/alu/.local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alu/.local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alu/.local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alu/.local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/alu/proj/felicia/__init__.py", line 51, in get_response_all
    for file in os.listdir('app/results'):
FileNotFoundError: [Errno 2] No such file or directory: 'app/results'
2024-04-11 19:16:58 - INFO - graceful_shutdown
